### PR TITLE
Upgrade to npm-groovy-lint 12.0.0

### PR DESCRIPTION
**Pull request by nvuillam**
Minimum java version is now 17

### CODE REVIEW

**Comment by nvuillam** [comment]
@stevenh oops with 12.0.0 :(
Help ?  ❤️

**Comment by djukxe** [comment]
Hi @nvuillam I would like to give it a shot 🔥 
Could you please run test workflow on current 2.0.0 version? 
It seems tests were already failing back then but runs history have been purged and I would like to be sure I get same error when I test locally

**Comment by stevenh** [comment]
I do have a big rewrite of the tests pending, as I found that currently they are very dependent on internal state, so when running locally, including independently they are very flaky.

Haven't had much time recently as been busy at work. Hopefully in the next few weeks, todays job is getting [CodeNarc fix](https://github.com/CodeNarc/CodeNarc/pull/754) in kindly done by @chrismair 👍

**Comment by nvuillam** [comment]
@stevenh that's great, many thanks !

If you think @djukxe can help you, please invite him to work on your fork / branch :)

**Comment by stevenh** [comment]
Need to get some [more issues fixed in npm-groovy-lint first](https://github.com/nvuillam/npm-groovy-lint/pull/320).

**Pull request closed without merging**
