### PR TITLE
Upgrade to npm-groovy-lint v8.1.0

### PR DESCRIPTION
**Pull request by felipecrs**

### CODE REVIEW

**Comment by nvuillam** [comment]
Thanks a lot for your contribution :)
Will notify here once published (it's not done by CI yet)

**Comment by felipecrs** [comment]
In case you're interested in end-to-end automation regarding the release, checkout [semantic-release](https://github.com/semantic-release/semantic-release), it's mind-blowing if you never met it before.

I managed to integrate a vs code extension that I maintain with it if you're interested in a reference, the [`vscode-shellcheck`](https://github.com/timonwong/vscode-shellcheck).

**Comment by nvuillam** [comment]
I know shellcheck , i integrated it in Mega-Linter  :)
And your vs code extension is already listed in the doc -> https://nvuillam.github.io/mega-linter/descriptors/bash_shellcheck/
Don't hesitate to add a link to Mega-Linter on your extension :)

semantic-release looks quite interesting, thanks :)

**Comment by nvuillam** [comment]
New VsCode Groovy Lint soon available :)
image

**Comment by felipecrs** [comment]
> I know shellcheck, I integrated it in Mega-Linter :)
> And your vs code extension is already listed in the doc -> https://nvuillam.github.io/mega-linter/descriptors/bash_shellcheck/
> Don't hesitate to add a link to Mega-Linter on your extension :)

This is very cool, I'll surely find a way to reference it there.

> New VsCode Groovy Lint soon available :)
> image

Awesome, thanks so much. I'm already using it, it's working as expected.

**Pull request merged**
