### PR TITLE
v1.2.8 - npm audit fixes

### PR DESCRIPTION
**Pull request by proxxz**
- Upgrade mocha to 7.1.2
- Upgrade @types/mocha to 7.0.2
- Fixup package-lock.json

More about the discovered vulnerabilities:
- https://www.npmjs.com/advisories/1179
- https://www.npmjs.com/advisories/1500

### CODE REVIEW

**Comment by proxxz** [comment]
Failing suite is getting an error code 7 from curl on:

```bash
./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
curl -s https://codecov.io/bash | bash
```

**Review by nvuillam — APPROVED** [review]
Thanks for your contribution :)

And for codecov... it's just bad luck, sometimes it doesn't respond :/

**Comment by proxxz** [comment]
You're welcome :)

Yeah, that's the nature of the Internet and open source. :D

**Comment by nvuillam** [comment]
Published in v1.2.8 :)

**Pull request merged**
